'use client';
import {useEffect,useMemo,useState} from 'react'; import {supabaseBrowser} from '../../lib/supabase-browser';
const money=n=>new Intl.NumberFormat('uz-UZ').format(Number(n||0))+' so‘m';
export default function Dashboard(){const s=useMemo(()=>supabaseBrowser(),[]),[projects,setProjects]=useState([]),[expenses,setExpenses]=useState([]),[payments,setPayments]=useState([]),[logs,setLogs]=useState([]),[tab,setTab]=useState('hisobot'),[err,setErr]=useState('');async function load(){const [p,e,a,l]=await Promise.all([s.from('projects').select('*').order('created_at',{ascending:false}),s.from('expenses').select('*').order('created_at',{ascending:false}),s.from('payments').select('*').order('created_at',{ascending:false}),s.from('work_logs').select('*').order('created_at',{ascending:false})]);const x=[p,e,a,l].find(v=>v.error);if(x)setErr(x.error.message);setProjects(p.data||[]);setExpenses(e.data||[]);setPayments(a.data||[]);setLogs(l.data||[])}useEffect(()=>{load()},[]);const income=payments.reduce((a,x)=>a+Number(x.amount||0),0),cost=expenses.reduce((a,x)=>a+Number(x.total_amount||0),0);
async function project(e){e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await s.from('projects').insert({name:f.get('name'),client_name:f.get('client_name'),client_phone:f.get('client_phone'),address:f.get('address'),area_m2:+f.get('area_m2')||0,sell_price_m2:+f.get('sell_price_m2')||0,status:'Jarayonda'});if(error)return setErr(error.message);e.currentTarget.reset();load()}
async function expense(e){e.preventDefault();const f=new FormData(e.currentTarget),q=+f.get('quantity')||0,u=+f.get('unit_price')||0;const {error}=await s.from('expenses').insert({project_id:f.get('project_id'),category:f.get('category'),item_name:f.get('item_name'),quantity:q,unit:f.get('unit'),unit_price:u,total_amount:q*u,note:f.get('note')});if(error)return setErr(error.message);e.currentTarget.reset();load()}
async function payment(e){e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await s.from('payments').insert({project_id:f.get('project_id'),amount:+f.get('amount')||0,note:f.get('note')});if(error)return setErr(error.message);e.currentTarget.reset();load()}
async function log(e){e.preventDefault();const f=new FormData(e.currentTarget),{data:{user}}=await s.auth.getUser();const {error}=await s.from('work_logs').insert({worker_id:user.id,project_id:f.get('project_id'),work_description:f.get('work_description'),completed_m2:+f.get('completed_m2')||0,arrived_at:f.get('arrived_at')||null,left_at:f.get('left_at')||null});if(error)return setErr(error.message);e.currentTarget.reset();load()}
return <main className="shell"><header><div><div className="brand">ALUSAF</div><h1>Boshqaruv paneli</h1></div><button className="ghost" onClick={async()=>{await s.auth.signOut();location.href='/login'}}>Chiqish</button></header><nav>{[['hisobot','Hisobot'],['obyekt','Obyektlar'],['xarajat','Xarajatlar'],['tolov','To‘lovlar'],['ishchi','Ishchilar']].map(([x,n])=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{n}</button>)}</nav>{err&&<div className="alert">{err}</div>}
{tab==='hisobot'&&<><section className="stats"><div className="stat"><span>Klientdan olingan</span><b>{money(income)}</b></div><div className="stat"><span>Jami xarajat</span><b>{money(cost)}</b></div><div className="stat"><span>Sof foyda</span><b>{money(income-cost)}</b></div><div className="stat"><span>Obyektlar</span><b>{projects.length}</b></div></section><section className="card"><h2>Obyektlar foydasi</h2>{projects.map(p=>{const i=payments.filter(x=>x.project_id===p.id).reduce((a,x)=>a+Number(x.amount),0),c=expenses.filter(x=>x.project_id===p.id).reduce((a,x)=>a+Number(x.total_amount),0);return <div className="row" key={p.id}><b>{p.name}</b><span>Tushum {money(i)}</span><span>Xarajat {money(c)}</span><strong>Foyda {money(i-c)}</strong></div>})}</section></>}
{tab==='obyekt'&&<section className="grid2"><form className="card form" onSubmit={project}><h2>Yangi obyekt</h2><input name="name" placeholder="Obyekt nomi" required/><input name="client_name" placeholder="Mijoz ismi"/><input name="client_phone" placeholder="Telefon"/><input name="address" placeholder="Manzil"/><input name="area_m2" type="number" step=".01" placeholder="Kvadrat m²"/><input name="sell_price_m2" type="number" placeholder="Sotuv narxi / m²"/><button className="btn">Saqlash</button></form><section className="card"><h2>Obyektlar</h2>{projects.map(p=><div className="item" key={p.id}><b>{p.name}</b><span>{p.client_name||'—'} · {p.area_m2} m² · {p.status}</span></div>)}</section></section>}
{tab==='xarajat'&&<section className="grid2"><form className="card form" onSubmit={expense}><h2>Xarajat kiritish</h2><select name="project_id" required><option value="">Obyekt</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><select name="category"><option>Alukobond</option><option>Profil</option><option>Samorez</option><option>Karkaz</option><option>Ishchi haqi</option><option>Transport</option><option>Rover/bukish</option><option>Boshqa</option></select><input name="item_name" placeholder="Material/xarajat nomi" required/><input name="quantity" type="number" step=".001" placeholder="Miqdor" required/><select name="unit"><option>list</option><option>dona</option><option>metr</option><option>m²</option><option>reys</option><option>kun</option><option>xizmat</option></select><input name="unit_price" type="number" step=".01" placeholder="Shu safargi birlik narxi" required/><input name="note" placeholder="Izoh"/><button className="btn">Saqlash</button></form><section className="card"><h2>Xarajatlar</h2>{expenses.slice(0,30).map(x=><div className="item" key={x.id}><b>{x.category}: {x.item_name}</b><span>{x.quantity} {x.unit} × {money(x.unit_price)} = {money(x.total_amount)}</span></div>)}</section></section>}
{tab==='tolov'&&<section className="grid2"><form className="card form" onSubmit={payment}><h2>Klient to‘lovi</h2><select name="project_id" required><option value="">Obyekt</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input name="amount" type="number" placeholder="Olingan summa" required/><input name="note" placeholder="Avans / keyingi to‘lov"/><button className="btn">Saqlash</button></form><section className="card"><h2>To‘lovlar</h2>{payments.map(x=><div className="item" key={x.id}><b>{money(x.amount)}</b><span>{x.note||'To‘lov'}</span></div>)}</section></section>}
{tab==='ishchi'&&<section className="grid2"><form className="card form" onSubmit={log}><h2>Bugungi ish hisoboti</h2><select name="project_id" required><option value="">Obyekt</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input name="work_description" placeholder="Bugun nima ish qilindi?" required/><input name="completed_m2" type="number" step=".01" placeholder="Bajarilgan m²"/><label>Kelgan vaqt</label><input name="arrived_at" type="time"/><label>Ketgan vaqt</label><input name="left_at" type="time"/><button className="btn">Hisobotni yuborish</button></form><section className="card"><h2>Kunlik hisobotlar</h2>{logs.slice(0,30).map(x=><div className="item" key={x.id}><b>{x.work_description}</b><span>{x.completed_m2} m² · {x.work_date}</span></div>)}</section></section>}</main>}
